### ISSUE TITLE
Possible linker error

### ISSUE THREAD

**Issue by Xophmeister** [nadavbra/bgen_parser#1]
I am trying to install `bgen_parser` on our environment for one of our end users and, after following your instructions, am being presented with what looks like a linker error when trying to import your library.

`bgenix` is installed and working correctly. I'm using a virtual environment with Python 3.6.10, Cython 0.29.15, numpy 1.18.1 and pandas 1.0.2. If I try an import in the Python REPL, I get the following:

```
>>> from bgen_parser import BgenParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/team152/dgx-venv/bgen_parser/bgen_parser/__init__.py", line 3, in <module>
    from .bgen_parser import BgenParser
  File "/software/team152/dgx-venv/bgen_parser/bgen_parser/bgen_parser.py", line 8, in <module>
    from cython_bgen_parser import PyBgenParser as CythonBgenParser
ImportError: /software/team152/dgx-venv/lib/python3.6/site-packages/cython_bgen_parser.cpython-36m-x86_64-linux-gnu.so: undefined symbol: uncompress
```

Any ideas how to proceed? Is that a symbol from zlib?

**Comment by nadavbra** [comment]
Hi,

Sorry for the problems you are encountering.

Can you try to uninstall bgen_parser and install it again? Please send me the full output of the installation process.
Also, what versions of Linux and gcc do you have on your machine?

Nadav

**Comment by Xophmeister** [comment]
Thanks for getting back to me.

> Also, what versions of Linux and gcc do you have on your machine?

```
mercury@farm5-head1 .../dgx-venv/bgen_parser$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mercury@farm5-head1 .../dgx-venv/bgen_parser$ uname -a
Linux farm5-head1 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

> Can you try to uninstall bgen_parser and install it again? Please send me the full output of the installation process.

```
mercury@farm5-head1 .../dgx-venv/bgen_parser$ env | grep BGENIX_DIR
BGENIX_DIR=/software/team152/dgx-venv/bgenix
mercury@farm5-head1 .../dgx-venv/bgen_parser$ python setup.py install
/software/hgi/installs/anaconda3/envs/py36/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/software/hgi/installs/anaconda3/envs/py36/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/bgen_parser
copying bgen_parser/__init__.py -> build/lib.linux-x86_64-3.6/bgen_parser
copying bgen_parser/bgen_parser.py -> build/lib.linux-x86_64-3.6/bgen_parser
running build_ext
skipping 'bgen_parser/py_bgen_parser.cpp' Cython extension (up-to-date)
building 'cython_bgen_parser' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/bgen_parser
gcc -pthread -B /software/hgi/installs/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/software/team152/dgx-venv/lib/python3.6/site-packages/numpy/core/include -I/software/team152/dgx-venv/bgenix/genfile/include -I/software/team152/dgx-venv/bgenix/3rd_party/zstd-1.1.0/lib -I/software/team152/dgx-venv/include -I/software/hgi/installs/anaconda3/envs/py36/include/python3.6m -c bgen_parser/py_bgen_parser.cpp -o build/temp.linux-x86_64-3.6/bgen_parser/py_bgen_parser.o -O3
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /software/team152/dgx-venv/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /software/team152/dgx-venv/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /software/team152/dgx-venv/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from bgen_parser/py_bgen_parser.cpp:617:
/software/team152/dgx-venv/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
gcc -pthread -B /software/hgi/installs/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/software/team152/dgx-venv/lib/python3.6/site-packages/numpy/core/include -I/software/team152/dgx-venv/bgenix/genfile/include -I/software/team152/dgx-venv/bgenix/3rd_party/zstd-1.1.0/lib -I/software/team152/dgx-venv/include -I/software/hgi/installs/anaconda3/envs/py36/include/python3.6m -c bgen_parser/BgenParser.cpp -o build/temp.linux-x86_64-3.6/bgen_parser/BgenParser.o -O3
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from bgen_parser/BgenParser.h:4:0,
                 from bgen_parser/BgenParser.cpp:4:
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp: In instantiation of ‘void genfile::bgen::v12::parse_probability_data_general(const genfile::bgen::v12::GenotypeDataBlock&, BitParser, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; BitParser = genfile::bgen::v12::impl::SpecialisedBitParser<8>]’:
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1099:38:   required from ‘void genfile::bgen::v12::parse_probability_data(const genfile::bgen::v12::GenotypeDataBlock&, Setter&) [with Setter = ProbArraySetter]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1053:27:   required from ‘void genfile::bgen::v12::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1628:32:   required from ‘void genfile::bgen::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1642:26:   required from ‘void genfile::bgen::read_and_parse_genotype_data_block(std::istream&, const genfile::bgen::Context&, Setter&, std::vector<unsigned char>*, std::vector<unsigned char>*) [with Setter = ProbArraySetter; std::istream = std::basic_istream<char>]’
bgen_parser/BgenParser.cpp:102:107:   required from here
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1265:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for( uint32_t allele = 0; allele < (pack.numberOfAlleles-1); ++allele ) {
                                   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp: In instantiation of ‘void genfile::bgen::v12::parse_probability_data_general(const genfile::bgen::v12::GenotypeDataBlock&, BitParser, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; BitParser = genfile::bgen::v12::impl::SpecialisedBitParser<16>]’:
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1107:38:   required from ‘void genfile::bgen::v12::parse_probability_data(const genfile::bgen::v12::GenotypeDataBlock&, Setter&) [with Setter = ProbArraySetter]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1053:27:   required from ‘void genfile::bgen::v12::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1628:32:   required from ‘void genfile::bgen::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1642:26:   required from ‘void genfile::bgen::read_and_parse_genotype_data_block(std::istream&, const genfile::bgen::Context&, Setter&, std::vector<unsigned char>*, std::vector<unsigned char>*) [with Setter = ProbArraySetter; std::istream = std::basic_istream<char>]’
bgen_parser/BgenParser.cpp:102:107:   required from here
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1265:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp: In instantiation of ‘void genfile::bgen::v12::parse_probability_data_general(const genfile::bgen::v12::GenotypeDataBlock&, BitParser, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; BitParser = genfile::bgen::v12::impl::BitParser]’:
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1115:38:   required from ‘void genfile::bgen::v12::parse_probability_data(const genfile::bgen::v12::GenotypeDataBlock&, Setter&) [with Setter = ProbArraySetter]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1053:27:   required from ‘void genfile::bgen::v12::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1628:32:   required from ‘void genfile::bgen::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1642:26:   required from ‘void genfile::bgen::read_and_parse_genotype_data_block(std::istream&, const genfile::bgen::Context&, Setter&, std::vector<unsigned char>*, std::vector<unsigned char>*) [with Setter = ProbArraySetter; std::istream = std::basic_istream<char>]’
bgen_parser/BgenParser.cpp:102:107:   required from here
/software/team152/dgx-venv/bgenix/genfile/include/genfile/bgen/bgen.hpp:1265:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
g++ -pthread -shared -B /software/hgi/installs/anaconda3/envs/py36/compiler_compat -L/software/hgi/installs/anaconda3/envs/py36/lib -Wl,-rpath=/software/hgi/installs/anaconda3/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/software/hgi/installs/anaconda3/envs/hgi_base/lib -Wl,-rpath-link,/software/hgi/installs/anaconda3/envs/hgi_base/lib -L/software/hgi/installs/anaconda3/envs/hgi_base/lib build/temp.linux-x86_64-3.6/bgen_parser/py_bgen_parser.o build/temp.linux-x86_64-3.6/bgen_parser/BgenParser.o /software/team152/dgx-venv/bgenix/build/libbgen.a /software/team152/dgx-venv/bgenix/build/3rd_party/zstd-1.1.0/libzstd.a -o build/lib.linux-x86_64-3.6/cython_bgen_parser.cpython-36m-x86_64-linux-gnu.so
running install_lib
creating /software/team152/dgx-venv/lib/python3.6/site-packages/bgen_parser
copying build/lib.linux-x86_64-3.6/bgen_parser/__init__.py -> /software/team152/dgx-venv/lib/python3.6/site-packages/bgen_parser
copying build/lib.linux-x86_64-3.6/bgen_parser/bgen_parser.py -> /software/team152/dgx-venv/lib/python3.6/site-packages/bgen_parser
copying build/lib.linux-x86_64-3.6/cython_bgen_parser.cpython-36m-x86_64-linux-gnu.so -> /software/team152/dgx-venv/lib/python3.6/site-packages
byte-compiling /software/team152/dgx-venv/lib/python3.6/site-packages/bgen_parser/__init__.py to __init__.cpython-36.pyc
byte-compiling /software/team152/dgx-venv/lib/python3.6/site-packages/bgen_parser/bgen_parser.py to bgen_parser.cpython-36.pyc
running install_egg_info
Writing /software/team152/dgx-venv/lib/python3.6/site-packages/bgen_parser-1.0-py3.6.egg-info
```

**Comment by nadavbra** [comment]
I want to make sure that you properly installed bgenix.
Please validate that you have the following within your BGENIX_DIR (`/software/team152/dgx-venv/bgenix`):

    build/libbgen.a
    build/3rd_party/zstd-1.1.0/libzstd.a

I tried to reinstall bgen_parser on another machine from scratch with similar versions to what you are using (Python 3.6, cython-0.29.15 numpy-1.18.2 pandas-1.0.2 python-dateutil-2.8.1 pytz-2019.3 six-1.14.0, gcc 7.5.0), and it worked (I was able to run `from bgen_parser import BgenParser`).

Here is the output of `python setup.py install`:

    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/bgen_parser
    copying bgen_parser/bgen_parser.py -> build/lib.linux-x86_64-3.6/bgen_parser
    copying bgen_parser/__init__.py -> build/lib.linux-x86_64-3.6/bgen_parser
    running build_ext
    cythoning bgen_parser/py_bgen_parser.pyx to bgen_parser/py_bgen_parser.cpp
    /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/temp_bgen_parser_install/bgen_parser/bgen_parser/py_bgen_parser.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'cython_bgen_parser' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/bgen_parser
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/numpy/core/include -I/tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include -I/tmp/temp_bgen_parser_install/third_party/bgenix/3rd_party/zstd-1.1.0/lib -I/usr/include/python3.6m -I/tmp/temp_bgen_parser_install/my_python/include/python3.6m -c bgen_parser/py_bgen_parser.cpp -o build/temp.linux-x86_64-3.6/bgen_parser/py_bgen_parser.o -O3
    In file included from /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                     from /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from bgen_parser/py_bgen_parser.cpp:617:
    /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/numpy/core/include -I/tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include -I/tmp/temp_bgen_parser_install/third_party/bgenix/3rd_party/zstd-1.1.0/lib -I/usr/include/python3.6m -I/tmp/temp_bgen_parser_install/my_python/include/python3.6m -c bgen_parser/BgenParser.cpp -o build/temp.linux-x86_64-3.6/bgen_parser/BgenParser.o -O3
    In file included from bgen_parser/BgenParser.h:4:0,
                     from bgen_parser/BgenParser.cpp:4:
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp: In instantiation of ‘void genfile::bgen::v12::parse_probability_data_general(const genfile::bgen::v12::GenotypeDataBlock&, BitParser, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; BitParser = genfile::bgen::v12::impl::SpecialisedBitParser<8>]’:
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1099:38:   required from ‘void genfile::bgen::v12::parse_probability_data(const genfile::bgen::v12::GenotypeDataBlock&, Setter&) [with Setter = ProbArraySetter]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1053:27:   required from ‘void genfile::bgen::v12::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1628:32:   required from ‘void genfile::bgen::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1642:26:   required from ‘void genfile::bgen::read_and_parse_genotype_data_block(std::istream&, const genfile::bgen::Context&, Setter&, std::vector<unsigned char>*, std::vector<unsigned char>*) [with Setter = ProbArraySetter; std::istream = std::basic_istream<char>]’
    bgen_parser/BgenParser.cpp:102:107:   required from here
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1265:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for( uint32_t allele = 0; allele < (pack.numberOfAlleles-1); ++allele ) {
                                       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp: In instantiation of ‘void genfile::bgen::v12::parse_probability_data_general(const genfile::bgen::v12::GenotypeDataBlock&, BitParser, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; BitParser = genfile::bgen::v12::impl::SpecialisedBitParser<16>]’:
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1107:38:   required from ‘void genfile::bgen::v12::parse_probability_data(const genfile::bgen::v12::GenotypeDataBlock&, Setter&) [with Setter = ProbArraySetter]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1053:27:   required from ‘void genfile::bgen::v12::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1628:32:   required from ‘void genfile::bgen::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1642:26:   required from ‘void genfile::bgen::read_and_parse_genotype_data_block(std::istream&, const genfile::bgen::Context&, Setter&, std::vector<unsigned char>*, std::vector<unsigned char>*) [with Setter = ProbArraySetter; std::istream = std::basic_istream<char>]’
    bgen_parser/BgenParser.cpp:102:107:   required from here
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1265:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp: In instantiation of ‘void genfile::bgen::v12::parse_probability_data_general(const genfile::bgen::v12::GenotypeDataBlock&, BitParser, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; BitParser = genfile::bgen::v12::impl::BitParser]’:
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1115:38:   required from ‘void genfile::bgen::v12::parse_probability_data(const genfile::bgen::v12::GenotypeDataBlock&, Setter&) [with Setter = ProbArraySetter]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1053:27:   required from ‘void genfile::bgen::v12::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1628:32:   required from ‘void genfile::bgen::parse_probability_data(const byte_t*, const byte_t*, const genfile::bgen::Context&, Setter&) [with Setter = ProbArraySetter; genfile::byte_t = unsigned char]’
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1642:26:   required from ‘void genfile::bgen::read_and_parse_genotype_data_block(std::istream&, const genfile::bgen::Context&, Setter&, std::vector<unsigned char>*, std::vector<unsigned char>*) [with Setter = ProbArraySetter; std::istream = std::basic_istream<char>]’
    bgen_parser/BgenParser.cpp:102:107:   required from here
    /tmp/temp_bgen_parser_install/third_party/bgenix/genfile/include/genfile/bgen/bgen.hpp:1265:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/bgen_parser/py_bgen_parser.o build/temp.linux-x86_64-3.6/bgen_parser/BgenParser.o /tmp/temp_bgen_parser_install/third_party/bgenix/build/libbgen.a /tmp/temp_bgen_parser_install/third_party/bgenix/build/3rd_party/zstd-1.1.0/libzstd.a -o build/lib.linux-x86_64-3.6/cython_bgen_parser.cpython-36m-x86_64-linux-gnu.so
    running install_lib
    copying build/lib.linux-x86_64-3.6/cython_bgen_parser.cpython-36m-x86_64-linux-gnu.so -> /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages
    creating /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/bgen_parser
    copying build/lib.linux-x86_64-3.6/bgen_parser/bgen_parser.py -> /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/bgen_parser
    copying build/lib.linux-x86_64-3.6/bgen_parser/__init__.py -> /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/bgen_parser
    byte-compiling /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/bgen_parser/bgen_parser.py to bgen_parser.cpython-36.pyc
    byte-compiling /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/bgen_parser/__init__.py to __init__.cpython-36.pyc
    running install_egg_info
    Writing /tmp/temp_bgen_parser_install/my_python/lib/python3.6/site-packages/bgen_parser-1.0.egg-info

Maybe this can give you a hint as to what is going on in your case.

**Comment by Xophmeister** [comment]
Thanks, Nadav

I do have those .a files. My hunch is that there's something super-weird going on with my environment, which is managed by Conda. So I tried rebuilding everything, including the virtual environment, using non-Conda managed tools and, hey presto, it works fine.

Sorry for the wild goose chase. I'm not sure what Conda messed up.

**Comment by nadavbra** [comment]
I am glad this ended up working for you, one way or another ;)

**Comment by dbackenroth** [comment]
hi nadav, i'm having a similar issue. these are the commands i'm using to set up my environment:

virtualenv /vol/sci/bio/data/shai.carmi/db2175/ukbb_py --python python3
source ukbb_py/bin/activate.csh
pip install Cython
pip install numpy
git clone https://github.com/nadavbra/bgen_parser.git
cd bgen_parser/
setenv BGENIX_DIR ~/bgen
python setup.py install
pip install pandas

then in python i have the following error:

[ukbb_py] <326|0>db2175@hm-04:~/vol_sci/bgen_parser% python
Python 3.6.11 | packaged by conda-forge | (default, Nov 27 2020, 18:57:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from bgen_parser import BgenParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vol/sci/bio/data/shai.carmi/db2175/bgen_parser/bgen_parser/__init__.py", line 3, in <module>
    from .bgen_parser import BgenParser
  File "/vol/sci/bio/data/shai.carmi/db2175/bgen_parser/bgen_parser/bgen_parser.py", line 8, in <module>
    from cython_bgen_parser import PyBgenParser as CythonBgenParser
ImportError: /vol/sci/bio/data/shai.carmi/db2175/ukbb_py/lib/python3.6/site-packages/cython_bgen_parser.cpython-36m-x86_64-linux-gnu.so: undefined symbol: uncompress

i do have **build/libbgen.a
build/3rd_party/zstd-1.1.0/libzstd.a**
in my BGENIX directory

like Xophmeister my python is managed by conda...

**Comment by nadavbra** [comment]
Xophmeister reported that using a non-conda Python made the problem go away. Can you try that as well?

**Comment by dbackenroth** [comment]
that works for me too. i guess not a surprise! thanks.
